@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.cuboiddroid.cuboidxpiggybank.datagen;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;