@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.cuboiddroid.cuboidxpiggybank.datagen.client;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;