@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.cuboiddroid.cuboidxpiggybank.network;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;